import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Clock3, FileText, RefreshCw, XCircle } from "lucide-react";
import api from "../api/axios.js";

const formatDate = (value) => { if (!value) return "—"; const date = new Date(value); if (Number.isNaN(date.getTime())) return "—"; return new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(date); };
const iconFor = (action = "") => { const text = action.toLowerCase(); if (text.includes("accept") || text.includes("approv")) return { Icon: CheckCircle2, className: "bg-emerald-100 text-emerald-600" }; if (text.includes("den") || text.includes("reject")) return { Icon: XCircle, className: "bg-rose-100 text-rose-600" }; if (text.includes("submit")) return { Icon: FileText, className: "bg-blue-100 text-blue-600" }; return { Icon: Clock3, className: "bg-amber-100 text-amber-600" }; };

export default function Timeline() {
    const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
    const load = useCallback(async () => { try { setLoading(true); setError(""); const { data } = await api.get("/documents"); const docs = Array.isArray(data?.data) ? data.data : []; const events = []; docs.forEach((doc) => { if (Array.isArray(doc.activity) && doc.activity.length) doc.activity.forEach((event, index) => events.push({ id: `${doc.id}-${index}`, document: doc.name, action: event.action, note: event.note, at: event.at || doc.createdAt })); else events.push({ id: `${doc.id}-created`, document: doc.name, action: "Submitted", note: doc.remark || "", at: doc.createdAt }); }); events.sort((a, b) => new Date(b.at || 0) - new Date(a.at || 0)); setItems(events); } catch (err) { console.error("TIMELINE:", err); setError(err.response?.data?.error || "Unable to load timeline."); } finally { setLoading(false); } }, []);
    // eslint-disable-next-line react-hooks/set-state-in-effect
    useEffect(() => { load(); }, [load]);
    if (loading) return <div className="space-y-4">{[1, 2, 3, 4].map((i) => <div key={i} className="h-24 animate-pulse rounded-2xl bg-slate-100" />)}</div>;
    if (error) return <div className="card border-rose-200 bg-rose-50 p-5"><p className="font-semibold text-rose-900">Timeline unavailable</p><p className="mt-1 text-sm text-rose-700">{error}</p><button onClick={load} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-rose-600 px-4 py-2 text-sm font-semibold text-white"><RefreshCw size={16} />Try Again</button></div>;
    return <div className="space-y-6 pb-8"><header><p className="text-xs font-bold tracking-[0.14em] text-indigo-700">DOCUMENT HISTORY</p><h1 className="page-title mt-2">Timeline</h1><p className="page-subtitle">See the activity history of your submissions.</p></header><div className="card p-6">{items.length === 0 ? <div className="py-12 text-center text-sm text-slate-500">No document activity yet.</div> : <div className="relative"><div className="absolute bottom-0 left-5 top-0 w-px bg-slate-200" /><div className="space-y-7">{items.map((item) => { const { Icon, className } = iconFor(item.action); return <div key={item.id} className="relative flex gap-4"><div className={`relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full ${className}`}><Icon size={18} /></div><div className="flex-1 rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-col gap-1 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-semibold text-slate-900">{item.action}</p><p className="mt-1 text-sm text-slate-600">{item.document}</p></div><span className="text-xs text-slate-400">{formatDate(item.at)}</span></div>{item.note && <p className="mt-3 rounded-lg bg-white p-3 text-sm text-slate-600">{item.note}</p>}</div></div>; })}</div></div>}</div></div>;
}
