export const OFFICES_BY_SECTOR = {
  "General Services Sector": ["Office of the Governor", "Provincial Information Office", "Provincial Jail Management Office", "Provincial Assessor's Office", "Provincial Administrator's Office", "Provincial Legal Office", "Bids and Awards Committee Office", "Provincial General Services Office", "Provincial Human Resource Management Office", "Provincial Budget Office", "Provincial Treasurer's Office", "Provincial Accountant's Office", "Provincial Planning and Development Office", "Provincial Internal Audit Services Office"],
  "Economic and Environmental Sector": ["Provincial Environment and Natural Resources Office", "Provincial Veterinary Office", "Provincial Tourism Promotions and Development Office", "Provincial Agriculturist Office", "Provincial Economic Enterprise Development Office", "Provincial Cooperative Development Office", "Provincial Community-Based Gender and Development Office", "Provincial Employment Services Office"],
  "Social and Health Services Sector": ["Provincial Health Office", "Aborlan Medicare Hospital", "Narra Municipal Hospital", "Southern Palawan Provincial Hospital", "Quezon Medicare Hospital", "Roxas Medicare Hospital", "Northern Palawan Provincial Hospital", "Francisco F. Ponce De Leon Memorial Hospital", "Coron District Hospital", "Cuyo District Hospital", "Dr. Jose Rizal District Hospital", "Bataraza District Hospital", "El Nido Community Hospital", "San Vicente District Hospital", "Araceli-Dumaran District Hospital", "Balabac District Hospital", "Sofronio Española District Hospital", "Provincial Social Welfare and Development Office", "Provincial Disaster Risk Reduction Management Office", "Community Affairs Division Office", "Sports Division Office"],
  "Legislative Services Sector": ["Vice Governor's Office", "Secretary to the Sangguniang Panlalawigan Office", "Office of the Sangguniang Panlalawigan", "Office of Board Member Juan Antonio Alvarez", "Office of Board Member Roseller S. Pineda", "Office of Board Member Nieves C. Rosento", "Office of Board Member Winston Arzaga", "Office of Board Member Ma. Angela V. Sabando", "Office of Board Member Al-Nashier M. Ibba", "Office of Board Member Ryan D. Maminta", "Office of Board Member Marivic H. Roxas", "Office of Board Member Ariston D. Arzaga", "Office of Board Member Rafael V. Ortega Jr.", "Office of Board Member Ferdinand P. Zaballa", "Office of Board Member Al-Shariff W. Ibba", "Office of Board Member SK Federation Luzviminda L. Bautista", "Office of Board Member Arnel Abrina"],
  "Infrastructure Services Sector": ["Provincial Engineer's Office", "Provincial Equipment and Pool Office"],
};
export const SECTORS = Object.keys(OFFICES_BY_SECTOR);
export const DEPARTMENTS = Object.values(OFFICES_BY_SECTOR).flat();
